#!/bin/bash

# CLI wrapper for script-builder

COMMAND=$1
SCRIPT_NAME=$2

if [ -z "$COMMAND" ] || [ -z "$SCRIPT_NAME" ]; then
  echo "Usage: ./build <dev|prod|create> <scriptName>"
  exit 1
fi

node index.js "$@"
